config/routes.rb
Rails.application.routes.draw do
  get   '/financial_calculator/',   to: 'calculators#edit',   as: 'edit_calculator'
  put   '/financial_calculator/',   to: 'calculators#update', as: 'calculator'
  patch '/financial_calculator/',   to: 'calculators#update'
  post  '/financial_calculator/',   to: 'calculators#update'
  root  'calculators#new'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/calculator.rb
class Calculator # < ActiveRecord::Base
  include ActiveModel::AttributeMethods
	include ActiveModel::Model

  attribute_method_suffix  '_as_percentage'
  define_attribute_methods :interest_rate, 
                           :inflation_rate, 
                           :post_retire_interest_rate, 
                           :retirement_tax_rate

  attr_accessor :current_savings,
                :interest_rate,
                :annual_contributions,
                :inflate_contributions,
                :inflation_rate,
                :current_age,
                :retirement_age,
                :withdraw_until_age,
                :post_retire_interest_rate,
                :retirement_tax_rate,
                :show_in_todays_dollars

  attr_reader :yearly_retirement_income

	validates_numericality_of :current_savings,
                            :interest_rate,
                            :annual_contributions,
                            :inflation_rate,
                            :current_age,
                            :retirement_age,
                            :withdraw_until_age,
                            :post_retire_interest_rate,
                            :retirement_tax_rate

	DEFAULT_VALUES = {
    current_savings: 100000.0,
    interest_rate: 8,
    annual_contributions: 20000.0,
    inflate_contributions: false,
    inflation_rate: 3,
    current_age: 45,
    retirement_age: 65,
    withdraw_until_age: 100,
    post_retire_interest_rate: 5,
    retirement_tax_rate: 7,
    show_in_todays_dollars: false
  }

  def initialize(params = DEFAULT_VALUES)

  	params.each do |attr, value|
  		public_send("#{attr}=", value)
  	end if params
    
  end

	def update #(attributes)
    if valid? 
      calculate
    else
      self
    end
  end

  def inflate_contributions?
    if @inflate_contributions == "1"
      true
    else
      false
    end
  end

  def show_in_todays_dollars?
    if @show_in_todays_dollars == "1"
      true
    else
      false
    end
  end

  private

    def attribute_as_percentage(attr)
      send("#{attr}").to_f / 100
    end

    # def make_boolean_of(value)
    #   return case value
    #     when "0" then false
    #     when 0 then false
    #     when "false" then false
    #     when "" then false
    #     when nil then false
    #     when false then false
    #     else true
    #   end
    # end

    def years_until_retirement
      @retirement_age.to_i - @current_age.to_i
    end

		def calculate

      Rails.logger.info (self.to_s)
	    current_savings = @current_savings.to_f

      current_savings = get_pre_retirement_calculations current_savings
      calculate_yearly_retirement current_savings

	    return self
	  end

    def get_pre_retirement_calculations current_savings

      current_contribution   = @annual_contributions.to_f
      
      years_until_retirement.to_i.times do 
        
        current_savings      = current_savings * (1 + interest_rate_as_percentage)
        current_savings      = current_savings + current_contribution
        
        if (inflate_contributions?)
          current_contribution = current_contribution * 
                                    (1 + inflation_rate_as_percentage)        
        end
      end

      current_savings #return
    end

    def calculate_yearly_retirement current_savings

      years_of_retirement  = @withdraw_until_age.to_i - @retirement_age.to_i
      inflation_rate_value = inflation_rate_as_percentage

      # To avoid divide by zero
      if (inflation_rate_value - post_retire_interest_rate_as_percentage == 0)
        inflation_rate_value = inflation_rate_value + 0.00000001
      end

      # http://www.financeformulas.net/
      numerator = post_retire_interest_rate_as_percentage - inflation_rate_value
      denominator = 1 - ((1 + inflation_rate_value)/
                            (1 + post_retire_interest_rate_as_percentage))**years_of_retirement

      yearly_ret_val_pretax = current_savings * (numerator/denominator)

      if (show_in_todays_dollars?)
        # PV * e ** rt 
        after_inflation_yearly_rate = 
            yearly_ret_val_pretax * 
              (Math::E ** ((-inflation_rate_as_percentage) * years_until_retirement))
        @yearly_retirement_income = 
          after_inflation_yearly_rate * (1 - retirement_tax_rate_as_percentage)
      else
        @yearly_retirement_income =  
          (yearly_ret_val_pretax) * (1 - retirement_tax_rate_as_percentage)
      end
      Rails.logger.info "yearly_retirement_income = #{yearly_retirement_income}"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calculators_controller.rb
class CalculatorsController < ApplicationController
  before_action :set_calculator, only: [:edit, :update]

  def new
    @calculator = Calculator.new
    respond_to do |format|
      format.html { render :edit }
      format.js
    end
  end

  # PATCH/PUT /calculators/1
  # PATCH/PUT /calculators/1.json
  def update
    Rails.logger.info "Begin update"
    if @calculator.update
      respond_to do |format|
        format.html { render :edit, notice: 'Calculator was successfully updated.' }
        format.js
        format.json { render :show, status: :ok, location: @calculator }
      end
    else
        Rails.logger.info "Calculator wasn't valid"
        respond_to do |format|
          format.js { render :edit }
          format.html { render :edit }
          format.json { render json: @calculator.errors, status: :unprocessable_entity }
        end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calculator
      Rails.logger.info "set_calculator"
      @calculator = Calculator.new(calculator_params)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calculator_params
      if params[:calculator]
        params.require(:calculator).permit(:current_savings, 
                                           :interest_rate, 
                                           :annual_contributions, 
                                           :inflate_contributions, 
                                           :inflation_rate, 
                                           :current_age, 
                                           :retirement_age, 
                                           :withdraw_until_age, 
                                           :post_retire_interest_rate, 
                                           :retirement_tax_rate, 
                                           :show_in_todays_dollars)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculators_helper.rb
module CalculatorsHelper
end

app/views/calculators/_form.html.haml
.text-center.container
  .well.well-lg#calculator
    %h1#title Retirement Calculator
    = form_for @calculator, url: calculator_path do |f|

      = render 'shared/error_messages', object: f.object
      
      .form-group.spacer
        = f.label :current_savings
        = f.text_field :current_savings, value: number_with_precision(@calculator.current_savings, :precision => 2), class: 'form-control'
      .form-group
        = f.label :interest_rate 
        = f.text_field :interest_rate, class: 'form-control' 

      .form-group
        = f.label :annual_contributions
        = f.text_field :annual_contributions, value: number_with_precision(@calculator.annual_contributions, :precision => 2), class: 'form-control'

      .form-group
        = f.label :inflate_contributions
        = f.check_box :inflate_contributions, class: 'form-control'

      .form-group
        = f.label :inflation_rate
        = f.text_field :inflation_rate, class: 'form-control'

      .form-group
        = f.label :current_age
        = f.number_field :current_age, class: 'form-control'

      .form-group
        = f.label :retirement_age
        = f.number_field :retirement_age, class: 'form-control'

      .form-group
        = f.label :withdraw_until_age
        = f.number_field :withdraw_until_age, class: 'form-control'

      .form-group
        = f.label :post_retire_interest_rate
        = f.text_field :post_retire_interest_rate, class: 'form-control'

      .form-group
        = f.label :retirement_tax_rate
        = f.text_field :retirement_tax_rate , class: 'form-control'

      .form-group
        = f.label :show_in_todays_dollars
        = f.check_box :show_in_todays_dollars, class: 'form-control'

      .actions
        = f.submit "Calculate!", class: 'btn btn-primary'

      %p
      .text-center.spacer#total
        %h4
          %span>= f.label :yearly_retirement_income
          \: 

          = number_to_currency @calculator.yearly_retirement_income

app/views/calculators/edit.html.erb
	<%= render 'form' %>

app/views/calculators/new.html.erb
	<%= render 'form' %>

app/views/calculators/update.js.erb
$('#yearly-total').html("<%= number_to_currency @calculator.yearly_retirement_income %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Retirement Calculator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>